language: go
go_import_path: p2p-port-forward

go:
  - '1.8'

sudo: required

services:
  - docker

install:
  - go get -u github.com/karalabe/xgo
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - xgo --targets=linux/amd64,darwin-10.11/amd64 .
